version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - ocramius
  - lcobucci
  - malukenho
  - dominikzogg
  versioning-strategy: increase
  ignore:
  - dependency-name: dflydev/fig-cookies
    versions:
    - 2.0.3
    - 3.0.0
  - dependency-name: lcobucci/jwt
    versions:
    - 4.0.0
    - 4.1.0
  - dependency-name: laminas/laminas-diactoros
    versions:
    - 2.5.0
  - dependency-name: laminas/laminas-httphandlerrunner
    versions:
    - 1.3.0
  - dependency-name: vimeo/psalm
    versions:
    - 3.18.2
